// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List                         = require("bs-platform/lib/js/list.js");
var Caml_obj                     = require("bs-platform/lib/js/caml_obj.js");
var Caml_format                  = require("bs-platform/lib/js/caml_format.js");
var StringUtils$AdventOfCode2017 = require("./StringUtils.js");

function solution(grid) {
  var sortAscending = function (row) {
    return List.sort(Caml_obj.caml_compare, row);
  };
  var lastMinusFirst = function (row) {
    return List.hd(List.rev(row)) - List.hd(row) | 0;
  };
  var list = List.map((function (row) {
          var row$1 = StringUtils$AdventOfCode2017.split(" ", row);
          return lastMinusFirst(sortAscending(List.map(Caml_format.caml_int_of_string, row$1)));
        }), StringUtils$AdventOfCode2017.split("\n", grid));
  return List.fold_left((function (acc, x) {
                return acc + x | 0;
              }), 0, list);
}

exports.solution = solution;
/* No side effect */
