// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List                         = require("bs-platform/lib/js/list.js");
var Caml_obj                     = require("bs-platform/lib/js/caml_obj.js");
var Caml_format                  = require("bs-platform/lib/js/caml_format.js");
var StringUtils$AdventOfCode2017 = require("./StringUtils.js");

function solution(grid) {
  var splitAndMakeInt = function (str) {
    return List.sort(Caml_obj.caml_compare, List.map(Caml_format.caml_int_of_string, StringUtils$AdventOfCode2017.split(" ", str)));
  };
  var lastMinusFirst = function (row) {
    return List.nth(row, List.length(row) - 1 | 0) - List.hd(row) | 0;
  };
  var list = List.map(lastMinusFirst, List.map(splitAndMakeInt, StringUtils$AdventOfCode2017.split("\n", grid)));
  return List.fold_left((function (acc, x) {
                return acc + x | 0;
              }), 0, list);
}

exports.solution = solution;
/* No side effect */
