// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List     = require("bs-platform/lib/js/list.js");
var $$String = require("bs-platform/lib/js/string.js");

function explode(s) {
  var n = s.length;
  if (n !== 0) {
    var _i = n - 1 | 0;
    var _acc = /* [] */0;
    while(true) {
      var acc = _acc;
      var i = _i;
      var acc_000 = $$String.sub(s, i, 1);
      var acc$1 = /* :: */[
        acc_000,
        acc
      ];
      if (i !== 0) {
        _acc = acc$1;
        _i = i - 1 | 0;
        continue ;
        
      } else {
        return acc$1;
      }
    };
  } else {
    return /* [] */0;
  }
}

function split(delimiter, s) {
  if (delimiter.length) {
    var result = List.fold_right((function (c, param) {
            var segment = param[1];
            var acc = param[0];
            if (c === delimiter) {
              var match = +(segment.length > 0);
              if (match !== 0) {
                return /* tuple */[
                        /* :: */[
                          segment,
                          acc
                        ],
                        ""
                      ];
              } else {
                return /* tuple */[
                        acc,
                        ""
                      ];
              }
            } else {
              return /* tuple */[
                      acc,
                      c + segment
                    ];
            }
          }), explode(s), /* tuple */[
          /* [] */0,
          ""
        ]);
    var segment = result[1];
    var words = result[0];
    if (segment === "") {
      return words;
    } else {
      return /* :: */[
              segment,
              words
            ];
    }
  } else {
    return explode(s);
  }
}

exports.explode = explode;
exports.split   = split;
/* No side effect */
