// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest                  = require("bs-jest/src/jest.js");
var Day3$AdventOfCode2017 = require("../src/day3.js");

describe("Day3", (function () {
        Jest.test("first case", (function () {
                return Jest.Expect[/* toBe */2](0)(Jest.Expect[/* expect */0](Day3$AdventOfCode2017.solution(1)));
              }));
        Jest.test("second case", (function () {
                return Jest.Expect[/* toBe */2](3)(Jest.Expect[/* expect */0](Day3$AdventOfCode2017.solution(12)));
              }));
        Jest.test("third case", (function () {
                return Jest.Expect[/* toBe */2](2)(Jest.Expect[/* expect */0](Day3$AdventOfCode2017.solution(23)));
              }));
        Jest.test("fourth case", (function () {
                return Jest.Expect[/* toBe */2](31)(Jest.Expect[/* expect */0](Day3$AdventOfCode2017.solution(1024)));
              }));
        return Jest.test("puzzle input", (function () {
                      return Jest.Expect[/* toBe */2](371)(Jest.Expect[/* expect */0](Day3$AdventOfCode2017.solution(368078)));
                    }));
      }));

/*  Not a pure module */
